name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for GitHub Pages
      run: |
        export NODE_OPTIONS="--max-old-space-size=4096"
        export VITE_GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        export VITE_BASE_PATH="/sense360-flash"
        npx vite build --base="/sense360-flash/"
        
    - name: Copy firmware files to deployment
      run: |
        echo "Copying firmware files to deployment directory..."
        mkdir -p ./dist/public/firmware
        cp -r ./public/firmware/* ./dist/public/firmware/
        echo "Firmware files copied successfully:"
        ls -la ./dist/public/firmware/
        echo "Verifying firmware file size:"
        du -h ./dist/public/firmware/sense360_v2.v2.0.0.factory.bin
        
    - name: Verify deployment structure
      run: |
        echo "Deployment directory structure:"
        find ./dist/public -name "*.bin" -type f
        echo "Total files in deployment:"
        find ./dist/public -type f | wc -l
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist/public
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      if: github.ref == 'refs/heads/main'